apiVersion: v1
kind: Service
metadata: 
  name: bravo
    labels:
      app: bravo
spec:
  type: NodePort
  ports:
  - name: braveport
    nodeport: 32092
    port: 92
    targetport: 9002
  selector
    app: bravo
